print(" --- Frame Buffer Size Example --- ")
h_res = int(input("Enter Horizontal Resolution: "))
v_res = int(input("Enter vertical Resolution: "))
bits = int(input("Enter bits per pixel: "))

print(" --- SOLUTION --- ")
t_pixel_count = (h_res * v_res)
print(f"Total Pixel Count : {t_pixel_count:,} pixels")
bits_per_pixel = (bits/8)
print(f"Bits to Bytes per Pixel : {bits_per_pixel} bytes/pixel")
t_memory = (t_pixel_count * bits_per_pixel)
print(f"Total memory : {t_memory:,} bytes")
b_to_mb = (t_memory/1048576)
print(f"MBS: {b_to_mb:.2f} MB")
